version: '3.8'

services:
  lexmind:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8522:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s

  # Development service (uncomment to use)
  # lexmind-dev:
  #   build:
  #     context: .
  #     target: builder
  #   ports:
  #     - "8522:8522"
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=development
  #   command: npm run dev 