version: '3.8'

services:
  lexmind:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8522:8522"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development 